### PR TITLE
camelCase edit and select

### PR DESCRIPTION
**Pull request by timelyportfolio**
see https://github.com/r-spatial/mapedit/issues/20 for discussion

### CODE REVIEW

**Comment by timelyportfolio** [comment]
In general I prefer to flatten arguments so they are as unnested as possible.  Documenting and auto-complete work much better this way, but I'm happy to consider doing differently.

**Comment by tim-salabim** [comment]
**leaflet** is why I brought it up. But how would we implement unnested `styleOptions()`? Two separate functions? Or name prefixes?

**Comment by timelyportfolio** [comment]
Since `CSS` is so massive, we can't take the arguments route, but I'm thinking `styleTrue = styleOptions( ...defaults...), styleFalse = styleOptions( ...defaults... )` and at least that way we can document better and add plenty of examples.  I have no interest in error checking/validating the `CSS`.

**Comment by tim-salabim** [comment]
Sounds good to me!

**Pull request merged**
