### PR TITLE
Fix out epsg

### PR DESCRIPTION
**Pull request by lbusett**
Currently, the object returned from `editFeatures` is in epsg 4326 irrespectively
frome the original projection. This PR would transform back the returned object 
in the CRS of the input if needed. 

## current behaviour: 

``` r
library(sf)
library(mapedit)
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"))
st_crs(nc)

Coordinate Reference System:
  EPSG: 4267 
  proj4string: "+proj=longlat +datum=NAD27 +no_defs"

nc <- editFeatures(nc, editor = "leafpm")
#click "DONE"
st_crs(nc) 

Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"

```

## After fix: 

``` r
nc <- editFeatures(nc, editor = "leafpm")
#click "DONE"
st_crs(nc)
Coordinate Reference System:
  EPSG: 4267 
  proj4string: "+proj=longlat +datum=NAD27 +no_defs"
```

### CODE REVIEW

**Comment by lbusett** [comment]
PS: I was working on the `leafpm` branch for other stuff, so I did the PR against your `leafpm` branch instead than on `master` to avoid making a mess. Sorry for that. Let me know if you want that I make another PM against `master`

**Comment by timelyportfolio** [comment]
@lbusett thanks so much for this.  I honestly thought we had already done this.  @tim-salabim are you ok with this change?

`leafpm` is the best target and thanks again for all your help and contributions.

**Comment by tim-salabim** [comment]
But we need to think about what to do with the existing `crs` argument which is rather useless then. Now that I think of it, it is a bit more involved than I thought. What if the incoming feature has `NA` as `crs`? We need an error then I think as we need to go to `4326` to be able to edit right?

**Comment by timelyportfolio** [comment]
@tim-salabim, I'm using the following for testing.

```
library(sf)
library(mapedit)
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"))
st_crs(nc)

with_crs <- editFeatures(nc, editor="leafpm")

no_crs <- editFeatures(
  st_set_crs(nc, NA_crs_),
  editor = "leafpm"
)
```

**Comment by tim-salabim** [comment]
I'll test and comment tomorrow.

**Comment by tim-salabim** [comment]
This doesnt work I'm afraid. In case of the nc dataset without crs we don't realise the problem because the coordinates are in fact longlat coordinate pairs. Try editing `mapview::trails[5, ]` without crs. The line is not displayed because it is well outside the longlat bounds as coordinates are utm. 

I think for now we should through an error if the incoming feature has no crs information. I don't think leaflet.draw or leaflet.pm support `L.CRS.Simple` which we would need to use for arbitrary crs.

**Comment by lbusett** [comment]
@tim-salabim Of course you're right.... I did not think that through enough...
I agree that it makes sense to just throw an error, for datasets without CRS. Would you like that I add that to the PR?

**Comment by tim-salabim** [comment]
Yes, that would be great! Do you have any objections that we add you as a contributor in the DESCRIPTION?

**Comment by timelyportfolio** [comment]
Also I am happy to deal with the merge conflict that I caused (whoops) on my end so don’t worry about that.  Thanks so much for your help and feedback.

**Comment by lbusett** [comment]
@tim-salabim No objections: I'd be glad of that Thanks for offering.
@timelyportfolio Ok: then do I wait for you to solve the merge conflict, and thenintroduce the NA CRS check?

**Comment by timelyportfolio** [comment]
@lbusett either works for me.  Don’t want to hold up progress.

**Comment by lbusett** [comment]
@timelyportfolio I committed adding the check on NA CRS. I do not know how "verbose" you like to be on error messages, so modify it as you see fit. Also, I usually currently use ".call = FALSE" on errors in packages, but again it is up to you.

**Comment by timelyportfolio** [comment]
@lbusett @tim-salabim I think this is a nice improvement, and as we worked through it I kept thinking in the back of my head that handling this problem could easily be a helpful package unto itself.  I wish I had some metrics on `mapedit` users and their geo skills, so we could tailor errors, warning, and other helpers.

**Comment by tim-salabim** [comment]
Yep, as you say, we're trying to be helpful here, not restrictive

**Pull request merged**
