### PR TITLE
Shiny modules for select and edit

### PR DESCRIPTION
**Pull request by timelyportfolio**
**WIP-not ready**

As discussed in #21, `Shiny` modules will allow a user to integrate `selectMap` into a bigger `Shiny` app and be much more flexible.  `selectMap` functionality will not change, but will now incorporate the new `Shiny` modules.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
dependencies and namespaces not properly handled, so I will resolve this

**Comment by timelyportfolio** [comment]
@tim-salabim, I think this pull is ready to merge now.  As a summary, it 

* adds modules for select and edit
* promotes `mapview` to `Imports`
* incorporates `mapview::addFeatures`
* removes circle Leaflet.draw tool in editMap
* defaults to repeatMode in editMap

**Comment by timelyportfolio** [comment]
@tim-salabim, want to push the button?

**Comment by tim-salabim** [comment]
hell yeah! :-)

**Comment by timelyportfolio** [comment]
thanks, @tim-salabim, I think I'll need to update the intro post again and then get to work on the next post.

**Comment by tim-salabim** [comment]
Why change the intro post? Was something broken in the last few days?

**Comment by timelyportfolio** [comment]
The only change for the intro post would be to the `selectMap` albersusa example.  `selectMap` uses `layerId` instead of `group` so the `leaflet` source map needs that change to work correctly.  I might just submit a pull with that correction along with the second post.

**Comment by tim-salabim** [comment]
sounds like a good idea

**Pull request merged**
