### PR TITLE
playback changes

### PR DESCRIPTION
**Pull request by timelyportfolio**
ref #37

* remove `playback`
* make `playback_lf` now `playback`
* add orig argument for playback with editFeatures

```
editFeatures(franconia[1:3,],record=TRUE, viewer=browserViewer()) %>%
  mapedit:::playback(franconia[1:3,])
```

### CODE REVIEW

**Comment by tim-salabim** [comment]
This, is simply fantastic!!! Thanks so much for implementing this! I am blown away!

**Comment by tim-salabim** [comment]
Though, I can't seem to save and playback?
```r
tst = editFeatures(franconia[1:3,],record=TRUE, viewer=browserViewer()) 
mapedit:::playback(tst)
```

**Comment by timelyportfolio** [comment]
Yep, without `mapedit:::playback(tst, franconia[1:3,])` there is no initial feature to modify.  Really struggling with how  to handle the case of only edit without provided `origsf`.

**Comment by tim-salabim** [comment]
Do you think it's too much overhead to record the original geometry (only) in the recorder as initial state? I think if the feature set to be modified is quite large, then editing via `Leaflet.Draw` will not be much fun anyway.

**Comment by timelyportfolio** [comment]
We can definitely try this.  We could store a reference to the original as String or binding.  I can see if we could store only the originals that are edited or deleted for initialization.

**Comment by timelyportfolio** [comment]
@tim-salabim, I just noticed that it seems we will only be able to store the original with `editFeatures()` and none of the other edit functions.   With some hard work, we could possibly inspect the map for the editable layer, but I don't think this would be worth the effort.  Is it ok to only store original for `editFeatures`?

**Comment by tim-salabim** [comment]
Yes, it is ok to only have the originals for `editFeatures`

**Pull request merged**
